### ISSUE TITLE
Dash sign (--) conversion

### ISSUE THREAD

**Issue by dennisqi** [buddax2/tmpNote#13]
When I type --, it automatically converted to —.
Is there a way to prevent this happen?

**Comment by buddax2** [comment]
It's a feature, not a bug :) 
Now you can do this from the context menu:
![image](https://user-images.githubusercontent.com/78059/53227122-fde98280-3685-11e9-91e4-8d81a2bdd42c.png)
 
But it will reset after relaunching the app. So I will fix this bug.
