### ISSUE TITLE
Cannot find the app on AppStore using the link in ReadMe

### ISSUE THREAD

**Issue by SuperAL** [buddax2/tmpNote#16]
![image](https://user-images.githubusercontent.com/17959173/63919189-d75f3680-ca70-11e9-88a3-a9c429754022.png)

**Comment by buddax2** [comment]
@SuperAL can you try this one? [https://itunes.apple.com/us/app/tmpnote/id1293664761](https://itunes.apple.com/us/app/tmpnote/id1293664761)

**Comment by SuperAL** [comment]
It's caused by my network, the link is fine!
