### ISSUE TITLE
Lost all the tmpNotes

### ISSUE THREAD

**Issue by PraveenViswanathan** [buddax2/tmpNote#19]
Hi - I have been using this app for close to an year now and had 5 workspaces with lot of data. Today, I opened tmpNote and I could not see any of saved messages. All the five workspaces are empty. How do I fix this and recover my messages?
![tmpNote_Issue](https://user-images.githubusercontent.com/43024336/86955825-0e7c8a80-c10d-11ea-859c-fea7f8eb5e0e.png)

**Comment by PraveenViswanathan** [comment]
@buddax2 @oyakub Please help with this issue.

**Comment by buddax2** [comment]
@PraveenViswanathan this might be caused by a sync issue. Please try to turn off synchronisation in settings.

**Comment by PraveenViswanathan** [comment]
@buddax2 I tried disabling the "Synchronization with iCloud" options in the preferences but it did not resolve the issue. Still not seeing my notes. Is there a way to check in the file system to look for those workspace notes? My immediate attention is on recovering those notes.

**Comment by buddax2** [comment]
The latest version of the app stores notes in this folder (replace `%userName%` with your username):
if sync is turned on: `/Users/%userName%/Library/Mobile\ Documents/iCloud~com~buddax2~tmpNote/Documents/`
sync turned off: `/Users/%userName%/Library/Containers/com.buddax2.tmpNote/Data/Documents/`
To open these folders you can run this command in your Terminal: 
`open /Users/%userName%/Library/Mobile\ Documents/iCloud~com~buddax2~tmpNote/Documents/`
`open /Users/%userName%/Library/Containers/com.buddax2.tmpNote/Data/Documents/`

Previous version was storing note in the User Defaults file. You can find it here: `/Users/%userName%/Library/Containers/com.buddax2.tmpNote/Data/Library/Preferences/com.buddax2.tmpNote.plist`

`open /Users/%userName%/Library/Containers/com.buddax2.tmpNote/Data/Library/Preferences/com.buddax2.tmpNote.plist`

I'm really sorry for this issue.

**Comment by PraveenViswanathan** [comment]
@buddax2 I could not find the old notes at any of the above path. Looks like all the container files (1-5) got deleted. That's fine its good to know the path details. I will close the issue for now.
