### ISSUE TITLE
Shortcut for switching mode

### ISSUE THREAD

**Issue by munierujp** [buddax2/tmpNote#20]
I'd like to switch modes by shortcut.

For example:

- ⌘⇧P: Plain text
- ⌘⇧M: Markdown preview
- ⌘⇧D: Drawing

**Comment by buddax2** [comment]
Thanks for the idea. I added the shortcuts with the lates update, but I set ⌘⇧T for Plain text (I don't even recall why not P).

**Comment by munierujp** [comment]
@buddax2 Great! Thank you 😄
