### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by ymgn-dev** [buddax2/tmpNote#26]
I bought it from the Mac app store, but it didn't work.

## Environment:
tmpNote ver3.2

macOS Monterey(Version 12.0.1)
MacBook Pro(13-inch, M1, 2020)

**Comment by buddax2** [comment]
Is there any crash report or something? Can you describe the behavior?

**Comment by ymgn-dev** [comment]
@buddax2 

Actually, it was working fine.
I didn't even know it was running because the icon in the menu bar was so lightly colored!

Thanks for a great product!

![CleanShot 2021-12-07 at 17 02 21@2x](https://user-images.githubusercontent.com/35668159/144996972-a0f397b4-93ce-43cb-af95-71d35c1607ad.png)

**Comment by buddax2** [comment]
Uhh, I will check the color. It should be white in this case.

Thanks for the feedback!

**Comment by ymgn-dev** [comment]
@buddax2 

May I close this Issue?
