### ISSUE TITLE
note copies to other slides 

### ISSUE THREAD

**Issue by shouq1818** [buddax2/tmpNote#27]
I cant use all 5 notes, when I write something in one note its copies to the other notes. so I'm just left with on slide only. Does someone know how to solve this issue
<img width="431" alt="Screen Shot 2021-12-09 at 12 22 53 PM" src="https://user-images.githubusercontent.com/95848464/145360223-f9e37ef1-30cd-43bd-a5b0-523b398cc01f.png">
?

**Comment by buddax2** [comment]
Should be fixed in version 3.3
