### ISSUE TITLE
Tabs not working. Notes delete after restarting the app.

### ISSUE THREAD

**Issue by AlFaLaSi97** [buddax2/tmpNote#28]
Hello,

I'm facing an issue where every time I either restart the app or restart my mac. all the data in the notes are gone and the different tabs in the notepad don't work anymore.

This started happening after I logged out of my iCloud account and logged back in.

Would appreciate all the help.
Thanks.

**Comment by buddax2** [comment]
Thank you for the report. I reproduced the issue and will fix it.

**Comment by AlFaLaSi97** [comment]
I should also follow up that a few friends of mine say that even downloading it the first time on a new machine has the same issue. It's probably a common issue on the latest version on the App Store.

Thanks again for the help and speedy reply :D

**Comment by AlFaLaSi97** [comment]
Hey bro o/
Any updates regarding this issue? I don't intend to rush you but your app is really important for me in every day use :D

**Comment by buddax2** [comment]
@AlFaLaSi97 sorry for the delay. I will try to find time on this weekend and fix the issue.

**Comment by AlFaLaSi97** [comment]
Hi bro,

Hope everything is going well.
Any updates regarding the notes?

**Comment by buddax2** [comment]
Hi @AlFaLaSi97. I released the fix yesterday.

**Comment by AlFaLaSi97** [comment]
Thank you for you support and response, I'm sorry I've missed your last comment and couldn't close the case sooner.

All the best bro :D
