### ISSUE TITLE
Version 3.3 fails to load when configured to load at startup

### ISSUE THREAD

**Issue by epmoyer** [buddax2/tmpNote#29]
After updating to 3.3 (via the App Store), the app fails to load on startup when configured to do so.
I saw the same behavior on both my machines (an M2 Air and an Intel MacBook Pro).

Disabling the preferences checkbox "launch tmpNote at system startup" fixes the problem (and then one needs to start the app manually after boot).  Disabling auto-launch from the terminal with `launchctl disable gui/501/com.buddax2.tmpNote.LauncherApplication` also worked.

When it fails to load at startup, I'd get a pop-up that says "The application can't be opened  -50", which is going to be frustrating to most users because there's no indication of which app is causing the problem (I also can't find it in the system logs).  I only figured it out through trial and error because tmpNote had pushed an update recently.

Disabling, rebooting, and re-enabling did not fix the problem, so I am just leaving auto-launch disabled for now.

<img width="282" alt="Screen Shot 2022-11-20 at 14 09 51" src="https://user-images.githubusercontent.com/136718/202929608-a0bec63f-9f3e-4b01-8431-1ea0b0725419.png">

I am currently running MacOs 12.6.1 (Monterey) on both the machines I've seen this problem on.

**Comment by buddax2** [comment]
Thanks for the report. I'll fix it ASAP.

**Comment by buddax2** [comment]
Should be fixed in the latest update.
