### ISSUE TITLE
Dark scrollbar background when using dark menu bar

### ISSUE THREAD

**Issue by luukjanssens** [buddax2/tmpNote#4]
The background colour of the scrollbar is dark when the dark menu bar is enabled:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/32478263/44022886-3a157c08-9ee9-11e8-9304-b97d167bc3c1.png">

Preventing a dark colour on the scrollbar or creating a dark version of the app would be nice!

**Comment by buddax2** [comment]
fixed by allowing the dark mode
