### ISSUE TITLE
CPU Usage at constant 1%

### ISSUE THREAD

**Issue by TanapTheTimid** [buddax2/tmpNote#7]
Viewing Activity Monitor shows that the CPU usage of the app is constantly at 1% even when the app window is not opened and battery impact is second only to Safari at 0.96, which is much greater than even Mail app (0.46). Although this is not much, it may be a cause for concern when trying to maximize battery.

**Comment by buddax2** [comment]
Thanks for reporting the issue. I will investigate it and fix. Hope you will change your 3stars review then :)

**Comment by TanapTheTimid** [comment]
Thanks for the response. I'll go and change my review.

**Comment by buddax2** [comment]
I believe I have fixed the CPU issue in the latest commit. You can build it and try or wait for the update in MacAppStore (I hope it will be available tomorrow)
